const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Arr.Acts.SplitString,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Arr.Exps.At,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{arkaplan: 0},
	{molekul0: 0},
	{answerArea: 0},
	{posX: 0},
	{posY: 0},
	{val: 0},
	{DragDrop: 0},
	{answerBtn: 0},
	{molekul1: 0},
	{molekul2: 0},
	{molekul3: 0},
	{molekul4: 0},
	{molekul5: 0},
	{molekul6: 0},
	{randomArray: 0},
	{Audio: 0},
	{Flash: 0},
	{Text: 0},
	{molekuller: 0},
	{randomKey: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	molekul0: class extends self.ISpriteInstance {},
	answerArea: class extends self.ISpriteInstance {},
	answerBtn: class extends self.ISpriteInstance {},
	molekul1: class extends self.ISpriteInstance {},
	molekul2: class extends self.ISpriteInstance {},
	molekul3: class extends self.ISpriteInstance {},
	molekul4: class extends self.ISpriteInstance {},
	molekul5: class extends self.ISpriteInstance {},
	molekul6: class extends self.ISpriteInstance {},
	randomArray: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	molekuller: class extends self.ISpriteInstance {}
}